# Generated by Django 4.2.16 on 2024-10-02 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base1", "0002_topic_room_host_messages_room_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room", options={"ordering": ["-updated", "-createds"]},
        ),
        migrations.AddField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="participants", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
